# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170219_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/img/avatars/'),
        ),
    ]
