# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_financials_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 2, 19, 19, 3, 11, 695000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
